home:
    path: /manager
    controller: App\Controller\ExplorerController::home
stub:
    path: /stub{path}
    controller: App\Controller\StubController::stubRequest
    requirements:
        path: .*
rest-get-all:
    path: /explorer/getAll
    controller: App\Controller\RestExplorerController::getAllStub
